
const restaurantList = [
  {
    data: {
      type: 'F',
      id: '81605',
      name: 'Seasons Restaurant',
      uuid: 'f0cd2354-affd-4d3e-822a-cacd218c9a5f',
      city: '80',
      area: 'Lalpur',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'nxlgpaxvcria5lfh1ktg',
      cuisines: ['North Indian', 'Asian', 'Biryani', 'Bakery'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 38,
      minDeliveryTime: 38,
      maxDeliveryTime: 38,
      slaString: '38 MINS',
      lastMileTravel: 4.400000095367432,
      slugs: {
        restaurant: 'seasons-restaurant-lalpur-lalpur',
        city: 'ranchi',
      },
      cityState: '80',
      address: 'Ground Floor, Shop 004, Sri Ram Neotia Arcade',
      locality: 'Hazaribag Road',
      parentId: 179710,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2400,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2400,
        message: '',
        title: 'Delivery Charge',
        amount: '2400',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: 'cid=6651669~p=16~eid=00000188-6ba9-491c-01a8-612b00701055',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '4.4 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '₹125 OFF',
        subHeader: 'ABOVE ₹249',
        discountTag: 'FLAT DEAL',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '81605',
        deliveryTime: 38,
        minDeliveryTime: 38,
        maxDeliveryTime: 38,
        lastMileTravel: 4.400000095367432,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '3.9',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    data: {
      type: 'F',
      id: '204404',
      name: 'The Cake Gallery',
      uuid: 'a14729e3-639d-4950-a1b4-2dfe2a98560e',
      city: '80',
      area: 'Ashok Nagar',
      totalRatingsString: '100+ ratings',
      cloudinaryImageId: 'fcrkviangq70el8vvqtv',
      cuisines: ['Bakery', 'Snacks'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 35,
      minDeliveryTime: 35,
      maxDeliveryTime: 35,
      slaString: '35 MINS',
      lastMileTravel: 0.5,
      slugs: {
        restaurant: 'the-cake-gallery-ashok-nagar-ashok-nagar',
        city: 'ranchi',
      },
      cityState: '80',
      address: 'Old A G Colony, Kadru, Ashok Nagar, Ranchi, Jharkhand, India',
      locality: 'Old A G Colony',
      parentId: 206262,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 1900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 1900,
        message: '',
        title: 'Delivery Charge',
        amount: '1900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.5 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '50% OFF',
        subHeader: 'UPTO ₹100',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '204404',
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        lastMileTravel: 0.5,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.5',
      totalRatings: 100,
      new: false,
    },
    subtype: 'basic',
  },
  {
    data: {
      type: 'F',
      id: '646651',
      name: 'Dining In The Sky',
      uuid: '90880763-1b8b-4af5-b18d-69c48299aa83',
      city: '80',
      area: 'Lalpur',
      totalRatingsString: '20+ ratings',
      cloudinaryImageId: '2a4ccd10f1d519f0e11020bfc0617a0a',
      cuisines: ['Chinese', 'Biryani', 'Fast Food'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 40,
      minDeliveryTime: 40,
      maxDeliveryTime: 40,
      slaString: '40 MINS',
      lastMileTravel: 4.800000190734863,
      slugs: {
        restaurant: 'dining-in-the-sky-lalpur-lalpur',
        city: 'ranchi',
      },
      cityState: '80',
      address:
        'Kali Mandir Road, Burdwan Compound, Lalpur,Ranchi Urban 2, Ranchi Urban 2,Ranchi, Jharkhand-834001',
      locality: 'Kali Mandir Road',
      parentId: 389937,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2400,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2400,
        message: '',
        title: 'Delivery Charge',
        amount: '2400',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: 'cid=6831178~p=19~eid=00000188-6ba9-491c-01a8-612c00701320',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '4.8 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '60% OFF',
        subHeader: 'UPTO ₹120',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '646651',
        deliveryTime: 40,
        minDeliveryTime: 40,
        maxDeliveryTime: 40,
        lastMileTravel: 4.800000190734863,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '3.7',
      totalRatings: 20,
      new: false,
    },
    subtype: 'basic',
  },
  {
    data: {
      type: 'F',
      id: '533934',
      name: 'ACS - 3',
      uuid: '06660455-739d-4882-8566-1e200711cce3',
      city: '80',
      area: 'Ashok Nagar',
      totalRatingsString: '100+ ratings',
      cloudinaryImageId: 'zqounfqgwrzth0pd9qk2',
      cuisines: ['Fast Food', 'Beverages'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 25,
      minDeliveryTime: 25,
      maxDeliveryTime: 25,
      slaString: '25 MINS',
      lastMileTravel: 1.399999976158142,
      slugs: {
        restaurant: 'acs---american-coffee-shop-hindpiri-hindpiri',
        city: 'ranchi',
      },
      cityState: '80',
      address:
        'Mepal Plaza, Ashok nagar Road No.2, Kadru, Ranchi, Urabn 3, Ranchi Urabn3, Ranchi, Jharkhand-834002',
      locality: 'Ashok Nagar Road',
      parentId: 320961,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 1900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 1900,
        message: '',
        title: 'Delivery Charge',
        amount: '1900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.3 kms',
      hasSurge: false,
      sla: {
        restaurantId: '533934',
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        lastMileTravel: 1.399999976158142,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.1',
      totalRatings: 100,
      new: false,
    },
    subtype: 'basic',
  },
  {
    data: {
      type: 'F',
      id: '428211',
      name: 'Louisville Chicken',
      uuid: '5a6b90f8-ba90-4e4d-ac21-592eb89daac9',
      city: '80',
      area: 'Kadru Main Road',
      totalRatingsString: '500+ ratings',
      cloudinaryImageId: 'hjp54yl3ue1zbeoghdkv',
      cuisines: ['Continental', 'Beverages', 'Desserts'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 26,
      minDeliveryTime: 26,
      maxDeliveryTime: 26,
      slaString: '26 MINS',
      lastMileTravel: 0.8999999761581421,
      slugs: {
        restaurant: 'louisville-chicken-hindpiri-hindpiri',
        city: 'ranchi',
      },
      cityState: '80',
      address:
        'RoboFood Cloud Kitchen, Rahat Colony, Kadru, Delatoli, Ranchi, Jharkhand 834002, India',
      locality: 'Rahat Colony',
      parentId: 238737,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 1900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 1900,
        message: '',
        title: 'Delivery Charge',
        amount: '1900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.8 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '30% OFF',
        subHeader: 'UPTO ₹75',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '428211',
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        lastMileTravel: 0.8999999761581421,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.2',
      totalRatings: 500,
      new: false,
    },
    subtype: 'basic',
  },
  {
    data: {
      type: 'F',
      id: '575817',
      name: 'Tbet Trail',
      uuid: '6ce35371-027a-4109-a9c0-6282b7505df4',
      city: '80',
      area: 'Lalpur',
      totalRatingsString: '100+ ratings',
      cloudinaryImageId: 'iippdcqp9zefruhad5az',
      cuisines: ['Chinese'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 55,
      minDeliveryTime: 55,
      maxDeliveryTime: 55,
      slaString: '55 MINS',
      lastMileTravel: 4.599999904632568,
      slugs: {
        restaurant: 'kitestar-hospitality-private-limited-lalpur-lalpur',
        city: 'ranchi',
      },
      cityState: '80',
      address:
        'NEW NARENDRA KUTIR RAJ NIKETAN CIRCULAR ROAD RANCHI, Ranchi Urban 2, Ranchi, Jharkhand-834001',
      locality: 'Circular Road \n',
      parentId: 351518,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2400,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2400,
        message: '',
        title: 'Delivery Charge',
        amount: '2400',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: 'cid=6793954~p=22~eid=00000188-6ba9-491c-01a8-612d00701617',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '4.5 kms',
      hasSurge: false,
      sla: {
        restaurantId: '575817',
        deliveryTime: 55,
        minDeliveryTime: 55,
        maxDeliveryTime: 55,
        lastMileTravel: 4.599999904632568,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.0',
      totalRatings: 100,
      new: false,
    },
    subtype: 'basic',
  },
  {
    data: {
      type: 'F',
      id: '85080',
      name: 'Hot Lips',
      uuid: 'af5c26e0-b28e-4737-a8e1-ce8ba1412a51',
      city: '80',
      area: 'Hinoo',
      totalRatingsString: '5000+ ratings',
      cloudinaryImageId: 'rpsl4m57jrwb6tglwpj2',
      cuisines: ['Chinese', 'Continental', 'Tandoor', 'Indian'],
      tags: [],
      costForTwo: 25000,
      costForTwoString: '₹250 FOR TWO',
      deliveryTime: 33,
      minDeliveryTime: 33,
      maxDeliveryTime: 33,
      slaString: '33 MINS',
      lastMileTravel: 2.5,
      slugs: {
        restaurant: 'hot-lips-hindpiri-hindpiri',
        city: 'ranchi',
      },
      cityState: '80',
      address: 'Hinoo Snarnan Tower, Hiinoo, Ranchi',
      locality: 'Shivpuri Colony \n',
      parentId: 97343,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 1900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 1900,
        message: '',
        title: 'Delivery Charge',
        amount: '1900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '2.5 kms',
      hasSurge: false,
      sla: {
        restaurantId: '85080',
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        lastMileTravel: 2.5,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.9',
      totalRatings: 5000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    data: {
      type: 'F',
      id: '624477',
      name: 'The Barbeque Company',
      uuid: '16b926ff-5961-4c01-a144-8aa420c0ee8b',
      city: '80',
      area: 'Ashok Nagar',
      totalRatingsString: 'Too Few Ratings',
      cloudinaryImageId: 'vfdysv8efxqebsv0plrz',
      cuisines: [
        'Barbecue',
        'North Indian',
        'Chinese',
        'Tandoor',
        'Beverages',
        'Thalis',
      ],
      tags: [],
      costForTwo: 160000,
      costForTwoString: '₹1600 FOR TWO',
      deliveryTime: 32,
      minDeliveryTime: 32,
      maxDeliveryTime: 32,
      slaString: '32 MINS',
      lastMileTravel: 0.6000000238418579,
      slugs: {
        restaurant: 'the-barbeque-company-hindpiri-hindpiri',
        city: 'ranchi',
      },
      cityState: '80',
      address:
        "#1006, 1st Floor, Skyline Mall, opp. Lal's Hospital, Kadru, Ranchi, Jharkhand 834002, India",
      locality: 'Skyline Mall',
      parentId: 205033,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 1900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 1900,
        message: '',
        title: 'Delivery Charge',
        amount: '1900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.6 kms',
      hasSurge: false,
      sla: {
        restaurantId: '624477',
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        lastMileTravel: 0.6000000238418579,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '--',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    data: {
      type: 'F',
      id: '651586',
      name: 'Capitol Residency',
      uuid: '57c381be-bb73-402e-a072-94a3177f86f6',
      city: '80',
      area: 'Hindpiri',
      totalRatingsString: '50+ ratings',
      cloudinaryImageId: 'd4eb7e534d869d892212137d548c1cea',
      cuisines: ['Indian', 'Seafood', 'Biryani'],
      tags: [],
      costForTwo: 80000,
      costForTwoString: '₹800 FOR TWO',
      deliveryTime: 42,
      minDeliveryTime: 42,
      maxDeliveryTime: 42,
      slaString: '42 MINS',
      lastMileTravel: 1.7000000476837158,
      slugs: {
        restaurant: 'capitol-residency-hindpiri-hindpiri',
        city: 'ranchi',
      },
      cityState: '80',
      address: 'Station Road,Ranchi',
      locality: 'Capitol Residency',
      parentId: 392247,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 1900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 1900,
        message: '',
        title: 'Delivery Charge',
        amount: '1900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: 'cid=6831080~p=25~eid=00000188-6ba9-491c-01a8-612e00701967',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.7 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '20% OFF',
        subHeader: 'UPTO ₹50',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '651586',
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        lastMileTravel: 1.7000000476837158,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.0',
      totalRatings: 50,
      new: false,
    },
    subtype: 'basic',
  },
  {
    data: {
      type: 'F',
      id: '81230',
      name: 'KFC',
      uuid: 'd3dff899-5a4a-4015-aed8-ecc2b70cdb50',
      city: '80',
      area: 'Kanka',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: '56c9ab92bd79745fd152a30fa2525426',
      cuisines: ['Burgers', 'Biryani', 'American', 'Snacks', 'Fast Food'],
      tags: [],
      costForTwo: 45000,
      costForTwoString: '₹450 FOR TWO',
      deliveryTime: 30,
      minDeliveryTime: 30,
      maxDeliveryTime: 30,
      slaString: '30 MINS',
      lastMileTravel: 2.299999952316284,
      slugs: {
        restaurant: 'kfc-station-road-test-ranchi',
        city: 'ranchi',
      },
      cityState: '80',
      address: 'KFC Ranchi,Siramtolichowk Station Road,Pin-834001',
      locality: 'Siromtoli',
      parentId: 547,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 1900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 1900,
        message: '',
        title: 'Delivery Charge',
        amount: '1900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '2.2 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '20% OFF',
        subHeader: 'UPTO ₹50',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '81230',
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        lastMileTravel: 2.299999952316284,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.1',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    data: {
      type: 'F',
      id: '456017',
      name: 'HYDERABAD BIRYANI HOUSE',
      uuid: '45077f87-1b9e-452f-913d-3df74a3ee428',
      city: '80',
      area: 'Kadru',
      totalRatingsString: '100+ ratings',
      cloudinaryImageId: 'g5l7gd2oulutzdjntwtk',
      cuisines: ['Biryani', 'Chinese', 'Desserts'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 28,
      minDeliveryTime: 28,
      maxDeliveryTime: 28,
      slaString: '28 MINS',
      lastMileTravel: 1,
      slugs: {
        restaurant: 'hyderabad-biryani-house-hindpiri-hindpiri',
        city: 'ranchi',
      },
      cityState: '80',
      address: '34, NEW A G CO-OPERATIVE COLONY KADRU, Ranchi',
      locality: 'New Ag Colony \n',
      parentId: 485,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 1900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 1900,
        message: '',
        title: 'Delivery Charge',
        amount: '1900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1 kms',
      hasSurge: false,
      sla: {
        restaurantId: '456017',
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        lastMileTravel: 1,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.8',
      totalRatings: 100,
      new: false,
    },
    subtype: 'basic',
  },
  {
    data: {
      type: 'F',
      id: '81770',
      name: 'The Best',
      uuid: '0064ba5b-e939-4607-8905-b61212832a8c',
      city: '80',
      area: 'Lalpur',
      totalRatingsString: '5000+ ratings',
      cloudinaryImageId: 'hfatbtcjvlbgzgl8jv3o',
      cuisines: ['North Indian', 'South Indian', 'Chinese'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 41,
      minDeliveryTime: 41,
      maxDeliveryTime: 41,
      slaString: '41 MINS',
      lastMileTravel: 4.599999904632568,
      slugs: {
        restaurant: 'the-best-lalpur-lalpur',
        city: 'ranchi',
      },
      cityState: '80',
      address: 'R.S.Tower, Circular Road, Lalpur, Ranchi',
      locality: 'Circular Road',
      parentId: 17807,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2400,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2400,
        message: '',
        title: 'Delivery Charge',
        amount: '2400',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: 'cid=6788479~p=28~eid=00000188-6ba9-491c-01a8-612f00701c43',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '4.5 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '60% OFF',
        subHeader: 'UPTO ₹120',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '81770',
        deliveryTime: 41,
        minDeliveryTime: 41,
        maxDeliveryTime: 41,
        lastMileTravel: 4.599999904632568,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '3.8',
      totalRatings: 5000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    data: {
      type: 'F',
      id: '366822',
      name: 'Rolltastic',
      uuid: '0ad93b24-b686-4054-8480-9625e90eed9a',
      city: '80',
      area: 'Kadru',
      totalRatingsString: '100+ ratings',
      cloudinaryImageId: '569125ea5189e04534015057bce2e5ac',
      cuisines: ['North Indian', 'Fast Food', 'Burgers'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 35,
      minDeliveryTime: 35,
      maxDeliveryTime: 35,
      slaString: '35 MINS',
      lastMileTravel: 0.8999999761581421,
      slugs: {
        restaurant: 'rolltastic-hindpiri-hindpiri',
        city: 'ranchi',
      },
      cityState: '80',
      address:
        '1662/C-21 RAHAT COLONY ASHOK NAGAR, Ranchi Urban 2, Ranchi Urban 2, Ranchi, Jharkhand - 834002',
      locality: 'Rahat Colony',
      parentId: 171230,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 1900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 1900,
        message: '',
        title: 'Delivery Charge',
        amount: '1900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.8 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '30% OFF',
        subHeader: 'UPTO ₹75',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '366822',
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        lastMileTravel: 0.8999999761581421,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.5',
      totalRatings: 100,
      new: false,
    },
    subtype: 'basic',
  },
  {
    data: {
      type: 'F',
      id: '118957',
      name: 'The Cake',
      uuid: '74330b59-62fa-40c8-b0cd-bbf98983c8b5',
      city: '80',
      area: 'Kadru',
      totalRatingsString: '1000+ ratings',
      cloudinaryImageId: 't6ndimj7obsqhdd1wsmu',
      cuisines: ['Bakery'],
      tags: [],
      costForTwo: 15000,
      costForTwoString: '₹150 FOR TWO',
      deliveryTime: 28,
      minDeliveryTime: 28,
      maxDeliveryTime: 28,
      slaString: '28 MINS',
      lastMileTravel: 0.5,
      slugs: {
        restaurant: 'the-cake-ashoknagar-ashok-nagar',
        city: 'ranchi',
      },
      cityState: '80',
      address: 'Opp Rcp Complex Near Hanuman Mandir Kardu Ranchi',
      locality: 'Ashok Nagar',
      parentId: 206207,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 1900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 1900,
        message: '',
        title: 'Delivery Charge',
        amount: '1900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.5 kms',
      hasSurge: false,
      sla: {
        restaurantId: '118957',
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        lastMileTravel: 0.5,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.2',
      totalRatings: 1000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    data: {
      type: 'F',
      id: '81411',
      name: 'Punjabi Kitchen - Lalpur',
      uuid: 'e1259766-6285-405a-8a41-39f0f66f4f7f',
      city: '80',
      area: 'Lalpur',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'vsj0eahhmzrjmqczfbzd',
      cuisines: [
        'North Indian',
        'Tandoor',
        'Chinese',
        'Desserts',
        'Beverages1',
        'Healthy Food',
        'Asian',
      ],
      tags: [],
      costForTwo: 25000,
      costForTwoString: '₹250 FOR TWO',
      deliveryTime: 39,
      minDeliveryTime: 39,
      maxDeliveryTime: 39,
      slaString: '39 MINS',
      lastMileTravel: 4.800000190734863,
      slugs: {
        restaurant: 'punjabi-kitchen-lalpur-lalpur',
        city: 'ranchi',
      },
      cityState: '80',
      address: 'Opposite Kashayap Eye Hospital, Purulia Road, Ranchi,',
      locality: 'Purulia Road',
      parentId: 162346,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2400,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2400,
        message: '',
        title: 'Delivery Charge',
        amount: '2400',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: 'cid=6651968~p=31~eid=00000188-6ba9-491c-01a8-613000701f0e',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '4.8 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '60% OFF',
        subHeader: 'UPTO ₹120',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '81411',
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        lastMileTravel: 4.800000190734863,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.0',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    data: {
      type: 'F',
      id: '222953',
      name: 'Second Wife Restaurant',
      uuid: 'dd3e1990-e745-4402-847c-486d1888c831',
      city: '80',
      area: 'Nayatoli',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'qtl7nhy0pr1th9mkrzxb',
      cuisines: ['Afghani', 'Chinese', 'Indian'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 50,
      minDeliveryTime: 50,
      maxDeliveryTime: 50,
      slaString: '50 MINS',
      lastMileTravel: 4.199999809265137,
      slugs: {
        restaurant: 'second-wife-lalpur-lalpur',
        city: 'ranchi',
      },
      cityState: '80',
      address: 'Opposite SRS Cinema,Dangra Toli Chowk, Lalpur, Ranchi',
      locality: 'Dangartoli',
      parentId: 314148,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2400,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2400,
        message: '',
        title: 'Delivery Charge',
        amount: '2400',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '4.1 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '60% OFF',
        subHeader: 'UPTO ₹120',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '222953',
        deliveryTime: 50,
        minDeliveryTime: 50,
        maxDeliveryTime: 50,
        lastMileTravel: 4.199999809265137,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.6',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
];
export default restaurantList;
